0. 변수 초기화
```{r}
rm(list=ls())
```

1. 데이터
```{r}
conv_dat = read.table(file="data/convenience_store.txt", sep='\t', header=TRUE)
conv_dat = data.frame(Region=conv_dat[,1],id=conv_dat[,2],StoreNum=conv_dat[,7],Population=conv_dat[,8])
conv_dat = cbind(conv_dat, conv_dat$StoreNum/conv_dat$Population*1000)
colnames(conv_dat)[5] = "StorePerPopul"

trust_dat = read.table(file="data/social_trust.txt", sep='\t', header=TRUE)
crime_dat = read.table(file="data/crime_2019.txt", sep='\t', header=TRUE)
raped_dat = read.table(file="data/raped_total.txt", sep='\t', header=TRUE)
hit_dat = read.table(file="data/hit_and_run.txt", sep='\t', header=TRUE)
```

2. 구역 지정
```{r}
library(raster)
library(ggplot2)
library(dplyr)

korea = shapefile('map/TL_SCCO_SIG.shp')
korea = fortify(korea, region='SIG_CD')
seoul = korea[korea$id <= 11740, ]
gu_name = read.table(file="gu_name.txt", sep='\t', header=TRUE)
```

3. 서울 인구 당 편의점 지도 출력
```{r}
conv_map = merge(seoul, conv_dat, by='id')
ggplot() + geom_polygon(data=conv_map, aes(x=long, y=lat, group=group, fill=StorePerPopul), color='white') +
  scale_fill_gradient(low = "#DBEDFF", high = "#0081FF") +
  labs(fill = "편의점 수 * 1000 / 인구 수") +
  coord_fixed(ratio = 1.3) +
  ggtitle("서울 인구 당 편의점 분포") +
  geom_text(data =gu_name,
            aes(x = long, y = lat, label = paste(Region, StoreNum, sep = "\n")))
```

4. 사회적 신뢰 지도 출력
```{r}
trust_map = merge(seoul, trust_dat, by='id')
ggplot() + geom_polygon(data=trust_map, aes(x=long, y=lat, group=group, fill=Total), color='white') +
  scale_fill_gradient(low = "#DBEDFF", high = "#0081FF") +
  labs(fill = "종합 신뢰 지수") +
  coord_fixed(ratio = 1.3) +
  ggtitle("사회적 신뢰 지수") +
  geom_text(data =gu_name,
            aes(x = long, y = lat, label = paste(Region, StoreNum, sep = "\n")))
```

5. 범죄 발생 지도 출력
```{r}
crime_map = merge(seoul, crime_dat, by='id')
ggplot() + geom_polygon(data=crime_map, aes(x=long, y=lat, group=group, fill=Total), color='white') +
  scale_fill_gradient(low = "#DBEDFF", high = "#0081FF") +
  labs(fill = "종합 범죄 발생 건건수") +
  coord_fixed(ratio = 1.3) +
  ggtitle("범죄 발생 건수") +
  geom_text(data =gu_name,
            aes(x = long, y = lat, label = paste(Region, StoreNum, sep = "\n")))
```

5. 사회적 신뢰 상관 관계 분석
```{r}
library(corrplot)

trust_cor = cbind(conv_dat[,3], trust_dat[,3:9])
colnames(trust_cor)[1] = "Store"
trust_cor = cor(trust_cor)
corrplot(trust_cor, method="number")
```

5. 범죄 발생 상관 관계 분석
```{r}
crime_cor = cbind(conv_dat[,3], crime_dat[,3:14])
colnames(crime_cor)[1] = "Store"
crime_cor = cor(crime_cor)
corrplot(crime_cor, method="number")
```

5. 뺑소니 발생 상관 관계 분석
```{r}
hit_cor = cbind(conv_dat[,3], hit_dat[,3])
colnames(hit_cor) = c("Store", "Hit and Run")
hit_cor = cor(hit_cor)
corrplot(hit_cor, method="number")
```

5. 이중차분법
```{r}
ggplot(raped_dat, aes(x=Year, y=Total, colour=Started)) + 
  geom_vline(xintercept=2013) +
  ggtitle("여성 안심 편의점 이중차분법") +
  stat_summary(geom="line") +
  geom_line(stat="smooth",method = "lm", formula = y ~ 0 + I(1/x) + I((x-1)/x),
              size = 1.2, linetype ="dashed", alpha = 0.5) +
  annotate("text", x=2008, y=5600, label="y = 477.3x - 954003", size=3) +
  annotate("text", x=2016, y=8100, label="y = 348.37x - 693275", size=3)
```